# Generated by Django 4.2.5 on 2023-09-18 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do produto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.FloatField(blank=True, null=True)),
                ('foto_produto', models.ImageField(null=True, upload_to='fotos/%d/%m/%y/')),
                ('data_produto', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
